In [131]:
import pandas as pd

In [132]:
df = pd.read_csv('loan_sanction_test.csv')

In [133]:
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban

In [134]:
df.shape

(367, 12)

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [136]:
df['Gender'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
362    False
363    False
364    False
365    False
366    False
Name: Gender, Length: 367, dtype: bool

In [137]:
df['Loan_ID'].isnull()
df.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [138]:
df['Loan_ID'].unique()

array(['LP001015', 'LP001022', 'LP001031', 'LP001035', 'LP001051',
       'LP001054', 'LP001055', 'LP001056', 'LP001059', 'LP001067',
       'LP001078', 'LP001082', 'LP001083', 'LP001094', 'LP001096',
       'LP001099', 'LP001105', 'LP001107', 'LP001108', 'LP001115',
       'LP001121', 'LP001124', 'LP001128', 'LP001135', 'LP001149',
       'LP001153', 'LP001163', 'LP001169', 'LP001174', 'LP001176',
       'LP001177', 'LP001183', 'LP001185', 'LP001187', 'LP001190',
       'LP001203', 'LP001208', 'LP001210', 'LP001211', 'LP001219',
       'LP001220', 'LP001221', 'LP001226', 'LP001230', 'LP001231',
       'LP001232', 'LP001237', 'LP001242', 'LP001268', 'LP001270',
       'LP001284', 'LP001287', 'LP001291', 'LP001298', 'LP001312',
       'LP001313', 'LP001317', 'LP001321', 'LP001323', 'LP001324',
       'LP001332', 'LP001335', 'LP001338', 'LP001347', 'LP001348',
       'LP001351', 'LP001352', 'LP001358', 'LP001359', 'LP001361',
       'LP001366', 'LP001368', 'LP001375', 'LP001380', 'LP001386',
       'LP001400', 'LP001407', 'LP001413', 'LP001415', 'LP001419',
       'LP001420', 'LP001428', 'LP001445', 'LP001446', 'LP001450',
       'LP001452', 'LP001455', 'LP001466', 'LP001471', 'LP001472',
       'LP001475', 'LP001483', 'LP001486', 'LP001490', 'LP001496',
       'LP001499', 'LP001500', 'LP001501', 'LP001517', 'LP001527',
       'LP001534', 'LP001542', 'LP001547', 'LP001548', 'LP001558',
       'LP001561', 'LP001563', 'LP001567', 'LP001568', 'LP001573',
       'LP001584', 'LP001587', 'LP001589', 'LP001591', 'LP001599',
       'LP001601', 'LP001607', 'LP001611', 'LP001613', 'LP001622',
       'LP001627', 'LP001650', 'LP001651', 'LP001652', 'LP001655',
       'LP001660', 'LP001662', 'LP001663', 'LP001667', 'LP001695',
       'LP001703', 'LP001718', 'LP001728', 'LP001735', 'LP001737',
       'LP001739', 'LP001742', 'LP001757', 'LP001769', 'LP001771',
       'LP001785', 'LP001787', 'LP001789', 'LP001791', 'LP001794',
       'LP001797', 'LP001815', 'LP001817', 'LP001818', 'LP001822',
       'LP001827', 'LP001831', 'LP001842', 'LP001853', 'LP001855',
       'LP001857', 'LP001862', 'LP001867', 'LP001878', 'LP001881',
       'LP001886', 'LP001906', 'LP001909', 'LP001911', 'LP001921',
       'LP001923', 'LP001933', 'LP001943', 'LP001950', 'LP001959',
       'LP001961', 'LP001973', 'LP001975', 'LP001979', 'LP001995',
       'LP001999', 'LP002007', 'LP002009', 'LP002016', 'LP002017',
       'LP002018', 'LP002027', 'LP002028', 'LP002042', 'LP002045',
       'LP002046', 'LP002047', 'LP002056', 'LP002057', 'LP002059',
       'LP002062', 'LP002064', 'LP002069', 'LP002070', 'LP002077',
       'LP002083', 'LP002090', 'LP002096', 'LP002099', 'LP002102',
       'LP002105', 'LP002107', 'LP002111', 'LP002117', 'LP002118',
       'LP002123', 'LP002125', 'LP002148', 'LP002152', 'LP002165',
       'LP002167', 'LP002168', 'LP002172', 'LP002176', 'LP002183',
       'LP002184', 'LP002186', 'LP002192', 'LP002195', 'LP002208',
       'LP002212', 'LP002240', 'LP002245', 'LP002253', 'LP002256',
       'LP002257', 'LP002264', 'LP002270', 'LP002279', 'LP002286',
       'LP002294', 'LP002298', 'LP002306', 'LP002310', 'LP002311',
       'LP002316', 'LP002321', 'LP002325', 'LP002326', 'LP002329',
       'LP002333', 'LP002339', 'LP002344', 'LP002346', 'LP002354',
       'LP002355', 'LP002358', 'LP002360', 'LP002375', 'LP002376',
       'LP002383', 'LP002385', 'LP002389', 'LP002394', 'LP002397',
       'LP002399', 'LP002400', 'LP002402', 'LP002412', 'LP002415',
       'LP002417', 'LP002420', 'LP002425', 'LP002433', 'LP002440',
       'LP002441', 'LP002442', 'LP002445', 'LP002450', 'LP002471',
       'LP002476', 'LP002482', 'LP002485', 'LP002495', 'LP002496',
       'LP002523', 'LP002542', 'LP002550', 'LP002551', 'LP002553',
       'LP002554', 'LP002561', 'LP002566', 'LP002568', 'LP002570',
       'LP002572', 'LP002581', 'LP002584', 'LP002592', 'LP002593',
       'LP002599', 'LP002604', 'LP002605', 'LP002609', 'LP002610',
       'LP002612', 'LP002614', 'LP002630', 'LP002635', 'LP002639',
       'LP002644', 'LP002651', 'LP002654', 'LP002657', 'LP002711',
       'LP002712', 'LP002721', 'LP002735', 'LP002744', 'LP002745',
       'LP002746', 'LP002747', 'LP002754', 'LP002759', 'LP002760',
       'LP002766', 'LP002769', 'LP002774', 'LP002775', 'LP002781',
       'LP002782', 'LP002786', 'LP002790', 'LP002791', 'LP002793',
       'LP002802', 'LP002803', 'LP002805', 'LP002806', 'LP002816',
       'LP002823', 'LP002825', 'LP002826', 'LP002843', 'LP002849',
       'LP002850', 'LP002853', 'LP002856', 'LP002857', 'LP002858',
       'LP002860', 'LP002867', 'LP002869', 'LP002870', 'LP002876',
       'LP002878', 'LP002879', 'LP002885', 'LP002890', 'LP002891',
       'LP002899', 'LP002901', 'LP002907', 'LP002920', 'LP002921',
       'LP002932', 'LP002935', 'LP002952', 'LP002954', 'LP002962',
       'LP002965', 'LP002969', 'LP002971', 'LP002975', 'LP002980',
       'LP002986', 'LP002989'], dtype=object)

In [139]:
df['ApplicantIncome'].unique()

array([ 5720,  3076,  5000,  2340,  3276,  2165,  2226,  3881, 13633,
        2400,  3091,  2185,  4166, 12173,  4666,  5667,  4583,  3786,
        9226,  1300,  1888,  2083,  3909,  3765,  5400,     0,  4363,
        7500,  3772,  2942,  2478,  6250,  3268,  2783,  2740,  3150,
        7350,  2267,  5833,  3643,  5629,  3644,  1750,  6500,  3666,
        4260,  4163,  2356,  6792,  8000,  2419,  3500,  4116,  5293,
        2750,  4402,  3613,  2779,  4720,  2415,  7016,  4968,  2101,
        4490,  2917,  4700,  3445,  7666,  2458,  3250,  4463,  4083,
        3900,  4750,  3583,  3189,  6356,  3413,  7950,  3829, 72529,
        4136,  8449,  4456,  4635,  3571,  3066,  3235,  5058,  3188,
       13518,  4364,  4766,  4609,  6260,  3333,  9719,  6835,  4452,
        2262,  3901,  2687,  2243,  3417,  1596,  4513,  4500,  4523,
        4742,  4082,  2922,  4167,  4243,  1516,  1762,   724,  3125,
        2333,  3350,  2500, 12500,  4667,  3073,  3321,  3391,  3343,
        3620,  4000,  4258,  2014,  4727,  3089,  6794, 32000, 10890,
       12941,  8703,  5900,  3071,  2463,  4855,  1599,  4246,  4333,
        5823,  7895,  4150,  2964,  5583,  2708,  3180,  2268,  1141,
        3042,  3564,  3958,  4483,  5225,  3017,  2431,  4912,  2918,
        5128, 15312,  4334,  4358, 10166,  4521,  9167, 13083,  7874,
        3785,  2654, 10000,  4796,  2000,  2540,  1900,  8706,  2855,
        3016,  3159,  1937,  2613,  4960,  3074,  4213,  2038,  2362,
        5333,  5384,  5708,  3754,  2914,  2747,  7830,  3507,  3747,
        2166,  2896,  5062,  5184,  2545,  2553,  3436,  2412,  5180,
       14911,  2860,  1173,  7600,  2157,  2231,  2274,  6166,  2513,
        3844,  3887,  3510,  2539,  2107,  3186,  3943,  2925,  3242,
        3863,  4028,  4010,  3719,  2858,  3833,  3007,  1850,  2792,
        2982, 18840,  2995,  3579,  3835,  3854,  3508,  1635, 24797,
        2773,  5769,  3634, 29167,  5530,  9000,  8750,  1972,  4983,
        8333,  3667,  3166,  3271,  2241,  1792,  2666,  6478,  3808,
        3729,  4120,  6300, 14987,   570,  2600,  2733,  3859,  6825,
        3708,  5314,  2366,  2066,  3767,  7859,  4283,  1700,  4768,
        3083,  2667,  1647,  3400, 16000,  2875,  5041,  6958,  5509,
        9699,  3621,  4709,  3015,  2292,  2360,  2623,  3972,  3522,
        6858,  8334,  2868,  3418,  8667,  2283,  5817,  5119,  5316,
        7603,  3791,  3132,  8550,  2269,  4009,  4158,  9200],
      dtype=int64)

In [140]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Gender']= encoder.fit_transform(df['Gender'])

In [141]:
df['Gender']

0      1
1      1
2      1
3      1
4      1
      ..
362    1
363    1
364    1
365    1
366    1
Name: Gender, Length: 367, dtype: int32

In [142]:
df.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,1,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,1,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,1,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,0,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,1,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,1,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,1,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban
10,LP001078,1,No,0,Not Graduate,No,3091,0,90.0,360.0,1.0,Urban
11,LP001082,1,Yes,1,Graduate,NaN,2185,1516,162.0,360.0,1.0,Semiurban
12,LP001083,1,No,3+,Graduate,No,4166,0,40.0,180.0,NaN,Urban
13,LP001094,1,Yes,2,Graduate,NaN,12173,0,166.0,360.0,0.0,Semiurban
14,LP001096,0,No,0,Graduate,No,4666,0,124.0,360.0,1.0,Semiurban
15,LP001099,1,No,1,Graduate,No,5667,0,131.0,360.0,1.0,Urban
16,LP001105,1,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.0,Urban
17,LP001107,1,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.0,Semiurban
18,LP001108,1,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.0,Urban
19,LP001115,1,No,0,Graduate,No,1300,3470,100.0,180.0,1.0,Semiurban

In [143]:
df['Married']= encoder.fit_transform(df['Married'])

In [144]:
df['Married']

0      1
1      1
2      1
3      1
4      0
      ..
362    1
363    1
364    0
365    1
366    0
Name: Married, Length: 367, dtype: int32

In [145]:
df.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1,1,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1,1,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,1,1,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,1,0,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,1,1,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,0,0,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,1,1,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,1,1,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,1,0,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban
10,LP001078,1,0,0,Not Graduate,No,3091,0,90.0,360.0,1.0,Urban
11,LP001082,1,1,1,Graduate,NaN,2185,1516,162.0,360.0,1.0,Semiurban
12,LP001083,1,0,3+,Graduate,No,4166,0,40.0,180.0,NaN,Urban
13,LP001094,1,1,2,Graduate,NaN,12173,0,166.0,360.0,0.0,Semiurban
14,LP001096,0,0,0,Graduate,No,4666,0,124.0,360.0,1.0,Semiurban
15,LP001099,1,0,1,Graduate,No,5667,0,131.0,360.0,1.0,Urban
16,LP001105,1,1,2,Graduate,No,4583,2916,200.0,360.0,1.0,Urban
17,LP001107,1,1,3+,Graduate,No,3786,333,126.0,360.0,1.0,Semiurban
18,LP001108,1,1,0,Graduate,No,9226,7916,300.0,360.0,1.0,Urban
19,LP001115,1,0,0,Graduate,No,1300,3470,100.0,180.0,1.0,Semiurban

In [146]:
df['Education']= encoder.fit_transform(df['Education'])

In [147]:
df['Education'] # Graduate = 0 , Not Graduate = 1

0      0
1      0
2      0
3      0
4      1
      ..
362    1
363    0
364    0
365    0
366    0
Name: Education, Length: 367, dtype: int32

In [148]:
df.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1,1,1,0,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1,1,2,0,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,1,1,2,0,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,1,0,0,1,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,1,1,0,1,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,0,0,1,1,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,1,1,2,1,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,1,1,2,0,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,1,0,0,1,No,2400,2400,123.0,360.0,1.0,Semiurban
10,LP001078,1,0,0,1,No,3091,0,90.0,360.0,1.0,Urban
11,LP001082,1,1,1,0,NaN,2185,1516,162.0,360.0,1.0,Semiurban
12,LP001083,1,0,3+,0,No,4166,0,40.0,180.0,NaN,Urban
13,LP001094,1,1,2,0,NaN,12173,0,166.0,360.0,0.0,Semiurban
14,LP001096,0,0,0,0,No,4666,0,124.0,360.0,1.0,Semiurban
15,LP001099,1,0,1,0,No,5667,0,131.0,360.0,1.0,Urban
16,LP001105,1,1,2,0,No,4583,2916,200.0,360.0,1.0,Urban
17,LP001107,1,1,3+,0,No,3786,333,126.0,360.0,1.0,Semiurban
18,LP001108,1,1,0,0,No,9226,7916,300.0,360.0,1.0,Urban
19,LP001115,1,0,0,0,No,1300,3470,100.0,180.0,1.0,Semiurban

In [149]:
df['Self_Employed']= encoder.fit_transform(df['Self_Employed'])

In [150]:
df['Self_Employed']

0      0
1      0
2      0
3      0
4      0
      ..
362    1
363    0
364    0
365    0
366    1
Name: Self_Employed, Length: 367, dtype: int32

In [151]:
df.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,1,0,0,1,0,3276,0,78.0,360.0,1.0,Urban
5,LP001054,1,1,0,1,1,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,0,0,1,1,0,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,1,1,2,1,0,3881,0,147.0,360.0,0.0,Rural
8,LP001059,1,1,2,0,2,13633,0,280.0,240.0,1.0,Urban
9,LP001067,1,0,0,1,0,2400,2400,123.0,360.0,1.0,Semiurban
10,LP001078,1,0,0,1,0,3091,0,90.0,360.0,1.0,Urban
11,LP001082,1,1,1,0,2,2185,1516,162.0,360.0,1.0,Semiurban
12,LP001083,1,0,3+,0,0,4166,0,40.0,180.0,NaN,Urban
13,LP001094,1,1,2,0,2,12173,0,166.0,360.0,0.0,Semiurban
14,LP001096,0,0,0,0,0,4666,0,124.0,360.0,1.0,Semiurban
15,LP001099,1,0,1,0,0,5667,0,131.0,360.0,1.0,Urban
16,LP001105,1,1,2,0,0,4583,2916,200.0,360.0,1.0,Urban
17,LP001107,1,1,3+,0,0,3786,333,126.0,360.0,1.0,Semiurban
18,LP001108,1,1,0,0,0,9226,7916,300.0,360.0,1.0,Urban
19,LP001115,1,0,0,0,0,1300,3470,100.0,180.0,1.0,Semiurban

In [152]:
df['Property_Area'].unique()

array(['Urban', 'Semiurban', 'Rural'], dtype=object)

In [153]:
df['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [154]:
df['Property_Area']= encoder.fit_transform(df['Property_Area'])

In [155]:
df.head(20)  #Urban = 2 , Semiurban = 1 , Rural = 0

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.0,NaN,2
4,LP001051,1,0,0,1,0,3276,0,78.0,360.0,1.0,2
5,LP001054,1,1,0,1,1,2165,3422,152.0,360.0,1.0,2
6,LP001055,0,0,1,1,0,2226,0,59.0,360.0,1.0,1
7,LP001056,1,1,2,1,0,3881,0,147.0,360.0,0.0,0
8,LP001059,1,1,2,0,2,13633,0,280.0,240.0,1.0,2
9,LP001067,1,0,0,1,0,2400,2400,123.0,360.0,1.0,1
10,LP001078,1,0,0,1,0,3091,0,90.0,360.0,1.0,2
11,LP001082,1,1,1,0,2,2185,1516,162.0,360.0,1.0,1
12,LP001083,1,0,3+,0,0,4166,0,40.0,180.0,NaN,2
13,LP001094,1,1,2,0,2,12173,0,166.0,360.0,0.0,1
14,LP001096,0,0,0,0,0,4666,0,124.0,360.0,1.0,1
15,LP001099,1,0,1,0,0,5667,0,131.0,360.0,1.0,2
16,LP001105,1,1,2,0,0,4583,2916,200.0,360.0,1.0,2
17,LP001107,1,1,3+,0,0,3786,333,126.0,360.0,1.0,1
18,LP001108,1,1,0,0,0,9226,7916,300.0,360.0,1.0,2
19,LP001115,1,0,0,0,0,1300,3470,100.0,180.0,1.0,1

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             367 non-null    int32
 2   Married            367 non-null    int32
 3   Dependents         357 non-null    object
 4   Education          367 non-null    int32
 5   Self_Employed      367 non-null    int32
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    int32
dtypes: float64(3), int32(5), int64(2), object(2)
memory usage: 27.4+ KB

In [157]:
df['Dependents']

0       0
1       1
2       2
3       2
4       0
       ..
362    3+
363     0
364     0
365     0
366     0
Name: Dependents, Length: 367, dtype: object

In [158]:
df['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [159]:
'3+'.replace('+', '')

'3'

In [160]:
df['Dependents'] = df['Dependents'].str.replace('+' ,'')

In [161]:
df['Dependents']

0      0
1      1
2      2
3      2
4      0
      ..
362    3
363    0
364    0
365    0
366    0
Name: Dependents, Length: 367, dtype: object

In [162]:
df['Dependents'].unique()

array(['0', '1', '2', '3', nan], dtype=object)

In [163]:
df['Loan_ID'].isnull().sum()

0

In [164]:
df['Gender'].isnull().sum()

0

In [165]:
df['Married'].isnull().sum()

0

In [166]:
df['Dependents'].isnull().sum()

10

In [167]:
print(df['Dependents'].dtype)

object

In [168]:
df['Dependents'] = df['Dependents'].astype(float)

In [169]:
df['Dependents']

0      0.0
1      1.0
2      2.0
3      2.0
4      0.0
      ...
362    3.0
363    0.0
364    0.0
365    0.0
366    0.0
Name: Dependents, Length: 367, dtype: float64

In [170]:
print(df['Dependents'].dtype)

float64

In [171]:
df['Dependents'].mean()

0.8291316526610645

In [172]:
df.fillna(0.8291316526610645, inplace=True)

In [173]:
df['Dependents'].isnull().sum()

0

In [174]:
df['Education'].isnull().sum()

0

In [175]:
df['Self_Employed'].isnull().sum()

0

In [176]:
df['ApplicantIncome'].isnull().sum()

0

In [177]:
df['CoapplicantIncome'].isnull().sum()

0

In [178]:
df['LoanAmount'].isnull().sum()

0

In [179]:
df['Loan_Amount_Term'].isnull().sum()

0

In [180]:
df['Credit_History'].isnull().sum()

0

In [181]:
print(df['Credit_History'].dtype)

float64

In [182]:
df['Credit_History'].isnull().sum()

0

In [183]:
df['Credit_History'].mean()

0.8257351987116374

In [184]:
df.fillna(0.8257351987116374, inplace=True)

In [185]:
df['Credit_History'].isnull().sum()

0

In [186]:
df.head(30)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0.0,0,0,5720,0,110.0,360.0,1.000000,2
1,LP001022,1,1,1.0,0,0,3076,1500,126.0,360.0,1.000000,2
2,LP001031,1,1,2.0,0,0,5000,1800,208.0,360.0,1.000000,2
3,LP001035,1,1,2.0,0,0,2340,2546,100.0,360.0,0.829132,2
4,LP001051,1,0,0.0,1,0,3276,0,78.0,360.0,1.000000,2
5,LP001054,1,1,0.0,1,1,2165,3422,152.0,360.0,1.000000,2
6,LP001055,0,0,1.0,1,0,2226,0,59.0,360.0,1.000000,1
7,LP001056,1,1,2.0,1,0,3881,0,147.0,360.0,0.000000,0
8,LP001059,1,1,2.0,0,2,13633,0,280.0,240.0,1.000000,2
9,LP001067,1,0,0.0,1,0,2400,2400,123.0,360.0,1.000000,1
10,LP001078,1,0,0.0,1,0,3091,0,90.0,360.0,1.000000,2
11,LP001082,1,1,1.0,0,2,2185,1516,162.0,360.0,1.000000,1
12,LP001083,1,0,3.0,0,0,4166,0,40.0,180.0,0.829132,2
13,LP001094,1,1,2.0,0,2,12173,0,166.0,360.0,0.000000,1
14,LP001096,0,0,0.0,0,0,4666,0,124.0,360.0,1.000000,1
15,LP001099,1,0,1.0,0,0,5667,0,131.0,360.0,1.000000,2
16,LP001105,1,1,2.0,0,0,4583,2916,200.0,360.0,1.000000,2
17,LP001107,1,1,3.0,0,0,3786,333,126.0,360.0,1.000000,1
18,LP001108,1,1,0.0,0,0,9226,7916,300.0,360.0,1.000000,2
19,LP001115,1,0,0.0,0,0,1300,3470,100.0,180.0,1.000000,1
20,LP001121,1,1,1.0,1,0,1888,1620,48.0,360.0,1.000000,2
21,LP001124,0,0,3.0,1,0,2083,0,28.0,180.0,1.000000,2
22,LP001128,2,0,0.0,0,0,3909,0,101.0,360.0,1.000000,2
23,LP001135,0,0,0.0,1,0,3765,0,125.0,360.0,1.000000,2
24,LP001149,1,1,0.0,0,0,5400,4380,290.0,360.0,1.000000,2
25,LP001153,1,0,0.0,0,0,0,24000,148.0,360.0,0.000000,0
26,LP001163,1,1,2.0,0,0,4363,1250,140.0,360.0,0.829132,2
27,LP001169,1,1,0.0,0,0,7500,3750,275.0,360.0,1.000000,2
28,LP001174,1,1,0.0,0,0,3772,833,57.0,360.0,0.829132,1
29,LP001176,1,0,0.0,0,0,2942,2382,125.0,180.0,1.000000,2

In [187]:
df['Credit_History'] = df['Credit_History'].astype(int)

In [188]:
df['Credit_History']

0      1
1      1
2      1
3      0
4      1
      ..
362    1
363    1
364    0
365    1
366    1
Name: Credit_History, Length: 367, dtype: int32

In [189]:
df.head(40)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0.0,0,0,5720,0,110.0,360.0,1,2
1,LP001022,1,1,1.0,0,0,3076,1500,126.0,360.0,1,2
2,LP001031,1,1,2.0,0,0,5000,1800,208.0,360.0,1,2
3,LP001035,1,1,2.0,0,0,2340,2546,100.0,360.0,0,2
4,LP001051,1,0,0.0,1,0,3276,0,78.0,360.0,1,2
5,LP001054,1,1,0.0,1,1,2165,3422,152.0,360.0,1,2
6,LP001055,0,0,1.0,1,0,2226,0,59.0,360.0,1,1
7,LP001056,1,1,2.0,1,0,3881,0,147.0,360.0,0,0
8,LP001059,1,1,2.0,0,2,13633,0,280.0,240.0,1,2
9,LP001067,1,0,0.0,1,0,2400,2400,123.0,360.0,1,1
10,LP001078,1,0,0.0,1,0,3091,0,90.0,360.0,1,2
11,LP001082,1,1,1.0,0,2,2185,1516,162.0,360.0,1,1
12,LP001083,1,0,3.0,0,0,4166,0,40.0,180.0,0,2
13,LP001094,1,1,2.0,0,2,12173,0,166.0,360.0,0,1
14,LP001096,0,0,0.0,0,0,4666,0,124.0,360.0,1,1
15,LP001099,1,0,1.0,0,0,5667,0,131.0,360.0,1,2
16,LP001105,1,1,2.0,0,0,4583,2916,200.0,360.0,1,2
17,LP001107,1,1,3.0,0,0,3786,333,126.0,360.0,1,1
18,LP001108,1,1,0.0,0,0,9226,7916,300.0,360.0,1,2
19,LP001115,1,0,0.0,0,0,1300,3470,100.0,180.0,1,1
20,LP001121,1,1,1.0,1,0,1888,1620,48.0,360.0,1,2
21,LP001124,0,0,3.0,1,0,2083,0,28.0,180.0,1,2
22,LP001128,2,0,0.0,0,0,3909,0,101.0,360.0,1,2
23,LP001135,0,0,0.0,1,0,3765,0,125.0,360.0,1,2
24,LP001149,1,1,0.0,0,0,5400,4380,290.0,360.0,1,2
25,LP001153,1,0,0.0,0,0,0,24000,148.0,360.0,0,0
26,LP001163,1,1,2.0,0,0,4363,1250,140.0,360.0,0,2
27,LP001169,1,1,0.0,0,0,7500,3750,275.0,360.0,1,2
28,LP001174,1,1,0.0,0,0,3772,833,57.0,360.0,0,1
29,LP001176,1,0,0.0,0,0,2942,2382,125.0,180.0,1,2
30,LP001177,0,0,0.0,1,0,2478,0,75.0,360.0,1,1
31,LP001183,1,1,2.0,0,0,6250,820,192.0,360.0,1,2
32,LP001185,1,0,0.0,0,0,3268,1683,152.0,360.0,1,1
33,LP001187,1,1,0.0,0,0,2783,2708,158.0,360.0,1,2
34,LP001190,1,1,0.0,0,0,2740,1541,101.0,360.0,1,2
35,LP001203,1,0,0.0,0,0,3150,0,176.0,360.0,0,1
36,LP001208,1,1,2.0,0,2,7350,4029,185.0,180.0,1,2
37,LP001210,1,1,0.0,0,1,2267,2792,90.0,360.0,1,2
38,LP001211,1,0,0.0,0,1,5833,0,116.0,360.0,1,2
39,LP001219,1,0,0.0,0,0,3643,1963,138.0,360.0,1,2

In [190]:
df['Dependents'] = df['Dependents'].astype(int)

In [191]:
df['Dependents']

0      0
1      1
2      2
3      2
4      0
      ..
362    3
363    0
364    0
365    0
366    0
Name: Dependents, Length: 367, dtype: int32

In [192]:
df.head(50)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.000000,1,2
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.000000,1,2
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.000000,1,2
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.000000,0,2
4,LP001051,1,0,0,1,0,3276,0,78.0,360.000000,1,2
5,LP001054,1,1,0,1,1,2165,3422,152.0,360.000000,1,2
6,LP001055,0,0,1,1,0,2226,0,59.0,360.000000,1,1
7,LP001056,1,1,2,1,0,3881,0,147.0,360.000000,0,0
8,LP001059,1,1,2,0,2,13633,0,280.0,240.000000,1,2
9,LP001067,1,0,0,1,0,2400,2400,123.0,360.000000,1,1
10,LP001078,1,0,0,1,0,3091,0,90.0,360.000000,1,2
11,LP001082,1,1,1,0,2,2185,1516,162.0,360.000000,1,1
12,LP001083,1,0,3,0,0,4166,0,40.0,180.000000,0,2
13,LP001094,1,1,2,0,2,12173,0,166.0,360.000000,0,1
14,LP001096,0,0,0,0,0,4666,0,124.0,360.000000,1,1
15,LP001099,1,0,1,0,0,5667,0,131.0,360.000000,1,2
16,LP001105,1,1,2,0,0,4583,2916,200.0,360.000000,1,2
17,LP001107,1,1,3,0,0,3786,333,126.0,360.000000,1,1
18,LP001108,1,1,0,0,0,9226,7916,300.0,360.000000,1,2
19,LP001115,1,0,0,0,0,1300,3470,100.0,180.000000,1,1
20,LP001121,1,1,1,1,0,1888,1620,48.0,360.000000,1,2
21,LP001124,0,0,3,1,0,2083,0,28.0,180.000000,1,2
22,LP001128,2,0,0,0,0,3909,0,101.0,360.000000,1,2
23,LP001135,0,0,0,1,0,3765,0,125.0,360.000000,1,2
24,LP001149,1,1,0,0,0,5400,4380,290.0,360.000000,1,2
25,LP001153,1,0,0,0,0,0,24000,148.0,360.000000,0,0
26,LP001163,1,1,2,0,0,4363,1250,140.0,360.000000,0,2
27,LP001169,1,1,0,0,0,7500,3750,275.0,360.000000,1,2
28,LP001174,1,1,0,0,0,3772,833,57.0,360.000000,0,1
29,LP001176,1,0,0,0,0,2942,2382,125.0,180.000000,1,2
30,LP001177,0,0,0,1,0,2478,0,75.0,360.000000,1,1
31,LP001183,1,1,2,0,0,6250,820,192.0,360.000000,1,2
32,LP001185,1,0,0,0,0,3268,1683,152.0,360.000000,1,1
33,LP001187,1,1,0,0,0,2783,2708,158.0,360.000000,1,2
34,LP001190,1,1,0,0,0,2740,1541,101.0,360.000000,1,2
35,LP001203,1,0,0,0,0,3150,0,176.0,360.000000,0,1
36,LP001208,1,1,2,0,2,7350,4029,185.0,180.000000,1,2
37,LP001210,1,1,0,0,1,2267,2792,90.0,360.000000,1,2
38,LP001211,1,0,0,0,1,5833,0,116.0,360.000000,1,2
39,LP001219,1,0,0,0,0,3643,1963,138.0,360.000000,1,2
40,LP001220,1,1,0,0,0,5629,818,100.0,360.000000,1,2
41,LP001221,0,0,0,0,0,3644,0,110.0,360.000000,1,2
42,LP001226,1,1,0,1,0,1750,2024,90.0,360.000000,1,1
43,LP001230,1,0,0,0,0,6500,2600,200.0,360.000000,1,1
44,LP001231,0,0,0,0,0,3666,0,84.0,360.000000,1,2
45,LP001232,1,1,0,0,0,4260,3900,185.0,0.829132,0,2
46,LP001237,1,1,0,1,0,4163,1475,162.0,360.000000,1,2
47,LP001242,1,0,0,1,0,2356,1902,108.0,360.000000,1,1
48,LP001268,1,0,0,0,0,6792,3338,187.0,0.829132,1,2
49,LP001270,1,1,3,1,1,8000,250,187.0,360.000000,1,1

In [193]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [194]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.0,1,2
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.0,1,2
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.0,1,2
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.0,0,2
4,LP001051,1,0,0,1,0,3276,0,78.0,360.0,1,2

In [195]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

# 👍🤗😎🎉